### ISSUE TITLE
Getting Ajax error when plugin is on (siteadministration menu ajax error)

### ISSUE THREAD

**Issue by neeesn** [frumbert/vimeoembed#2]
We had the problem in 2.9.4, and discovered that it was the vimeo filter that made the error.
if you have the filter installed, you can go into the filter folder and open the file filter.php.
At the bottom of the file remove the ?> and any empty lines.
Save the file
Clear cache
Reload.

Then it works again

**Comment by neeesn** [comment]
I can see theres a pull req. allready made - Just merge and release :-)

**Comment by frumbert** [comment]
NIce find. I normally leave the ending php marks of files for this very reason - guess I forgot with this one.
